services:
    kwiq-mq:
        image: golang:1.26.3-trixie
        container_name: kwiq-mq
        command: sleep infinity
    queue-consumer:
        image: python:3.12-slim
        container_name: queue-handler
        command: sleep infinity
    queue-publisher:
        image: python:3.12-slim
        container_name: queue-producer
        command: sleep infinity
