- name: Run CI
  hosts: myhosts
  tasks:
      - name: Check Python version
        command: python --version
        register: python_version

      - name: Print Python version
        debug:
            msg: 'Python version on {{ inventory_hostname }} is {{ python_version.stdout }}'
